### PR TITLE
Increase Serializer max Characters.

### PR DESCRIPTION
**Pull request by ex8**
# Description
Please include changes' summary that your pull request entails.

Fixes # (issue)

## Checklist

- [ ] Do unit tests run with no errors?
- [ ] Has coverage not decreased?
- [ ] Is your code concise and clean?
- [ ] Are the conf.py and installation sphinx updated with the new version?
- [ ] Is the __init__.py __version__ variable updated?

### CODE REVIEW

**Review by wagnerdelima — APPROVED** [review]

**Comment by ex8** [comment]
Graci @wagnerdelima for merging this. Is there any plan for release `2.1.4`? Your time and response are appreciated.

**Comment by wagnerdelima** [comment]
@ex8 I think this week. I just got back from vacation.

**Comment by wagnerdelima** [comment]
@ex8 just published a new 2.2.0 release.

**Comment by ex8** [comment]
@wagnerdelima - Thank you very much. I will switch to the `2.2.0` release on the next release of my application.

**Comment by wagnerdelima** [comment]
@ex8 let me know if you run into a problem.

**Comment by ex8** [comment]
@wagnerdelima for sure! Thanks for being on top of it.

Also super side note but going to live in Spain for a couple months, major excited :D :D

**Comment by wagnerdelima** [comment]
@ex8 welcome. Where are you from originally and where are you staying in Spain?

**Comment by ex8** [comment]
@wagnerdelima I am originally from California, but working remotely allows me to live around. I plan on staying on the coast. Malaga, Alicante, Valencia, Barcelona, then circle up to Madrid. Where are you located? If you don't mind me asking

**Comment by wagnerdelima** [comment]
I am in Málaga. Drop me an email when you are in Málaga. We can grab a beer.

**Comment by ex8** [comment]
That sounds perfect, I would love that. I will be there in the summer, what is the best way to contact you?

**Comment by wagnerdelima** [comment]
You can reach me on my email waglds at Gmail dot Com

**Comment by wagnerdelima** [comment]
@ex8 thanks! I just fixed it. 

Are you in Malaga yet?

**Comment by ex8** [comment]
@wagnerdelima I will be in Malaga starting June 16th!! I look forward to meeting !

I am currently in Marbella visiting a cousin so I am close by : )

**Pull request merged**
