### PR TITLE
Fix readme file

### PR DESCRIPTION
**Pull request by zubrzubr**
Just found that there is empty urls.py example in readme file

### CODE REVIEW

**Comment by zubrzubr** [comment]
@wagnerdelima could you check please?

**Comment by zubrzubr** [comment]
@wagnerdelima Sorry than, something wrong with page rendering on my PC.

image

is it the same for you?

**Comment by zubrzubr** [comment]
@wagnerdelima ok, there was mistake in readme file (no empty line after code block). I fixed it on my branch:

https://github.com/zubrzubr/drf-social-oauth2/tree/readme_file_fix

You could compare with master branch:

https://github.com/wagnerdelima/drf-social-oauth2

**Review by wagnerdelima — APPROVED** [review]

**Comment by wagnerdelima** [comment]
Indeed. Thank you.

**Pull request merged**
